[package]
name = "statik"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A pure rust lightweight 'fallback' minecraft server."
homepage = "https://sycrosity.github.io/statik-rs/"
repository = "https://github.com/Sycrosity/statik-rs/"
keywords = ["minecraft", "minecraft-server", "statik"]


[package.metadata]
msrv = "1.56.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
