use rand::{distributions::Uniform, Rng};
use statik_derive::Packet;

#[derive(Debug, Packet)]
#[packet_id = 0x01]
pub struct C2SEncryptionResponse {
    /// The server's public key, as bytes
    pub public_key: Vec<u8>,
    /// A sequence of random bytes generated by the server. Always of Length
    /// 4 when send by a notchian server.
    pub verify_token: Vec<u8>,
}
