[package]
name = "statik_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
byteorder = "1.4.3"
serde_json = "1.0.96"
serde = { version = "1.0.160", features = ["derive"] }
base64 = "0.21.0"
uuid = { version = "1.3.2", features = ["serde"] }
anyhow = "1.0.71"
rand = "0.8.5"

statik_derive = { path = "../statik_derive" }
statik_common = { path = "../statik_common" }
